input_data = [0, 3, 5, 7, 9, 8, 1, 2, 4, 6];
input_length = length(input_data);
normal_dft_data = my_dft(input_data);
normal_index = linspace(1, input_length, input_length);
add10zeros_length = input_length + 10;
add10zeros_data = zeros(1, add10zeros_length);
add10zeros_data(1:input_length) = input_data;
add10zeros_dft_data = my_dft(add10zeros_data);
add10zeros_index = linspace(1, add10zeros_length, add10zeros_length);
add990zeros_length = input_length + 990;
add990zeros_data = zeros(1, add990zeros_length);
add990zeros_data(1: input_length) = input_data;
add990zeros_dft_data = my_dft(add990zeros_data);
add990zeros_index = linspace(1, add990zeros_length, add990zeros_length);
%%%%
subplot(4,2,1);
stem(normal_index, abs(normal_dft_data));
xlabel('k');
ylabel('Amp');
title('原序列DFT幅度谱');
subplot(4,2,2);
stem(normal_index, phase(normal_dft_data));
xlabel('k');
ylabel('Phase');
title('原序列DFT相位谱');
%%%%%
subplot(4,2,3);
stem(add10zeros_index, abs(add10zeros_dft_data));
xlabel('k');
ylabel('Amp');
title('补10个0DFT幅度谱');
subplot(4,2,4);
stem(add10zeros_index, phase(add10zeros_dft_data));
xlabel('k');
ylabel('Phase');
title('补10个0DFT相位谱');
%%%%
subplot(4,2,5);
plot(add990zeros_index, abs(add990zeros_dft_data));
xlabel('k');
ylabel('Amp');
title('补990个0DFT幅度谱');
subplot(4,2,6);
plot(add990zeros_index, phase(add990zeros_dft_data));
xlabel('k');
ylabel('Phase');
title('补990个0DFT相位谱');
%%%%
subplot(4,2,7);
plot(add990zeros_index, abs(add990zeros_dft_data));
xlabel('k');
ylabel('Amp');
hold on;
stem(linspace(1,add990zeros_length,input_length), abs(normal_dft_data));
title('补990个0与原序列DFT幅度谱');
subplot(4,2,8);
plot(add990zeros_index, phase(add990zeros_dft_data));
xlabel('k');
ylabel('Phase');
hold on;
stem(linspace(1,add990zeros_length,input_length), phase(normal_dft_data));
title('补990个0与原序列DFT相位谱');