x_a = @(t)sin(2*pi*1*t)+0.5*sin(6*pi*1*t);
src_time = linspace(0,3,10000);
src_wave = x_a(src_time);
hz5_time = linspace(0,3,15);
hz5_wave = x_a(hz5_time);
hz5_back = interp1(hz5_time,hz5_wave,src_time,'pchip');
hz10_time = linspace(0,3,30);
hz10_wave = x_a(hz10_time);
hz10_back = interp1(hz10_time,hz10_wave,src_time,'pchip');
hz15_time = linspace(0,3,45);
hz15_wave = x_a(hz15_time);
hz15_back = interp1(hz15_time,hz15_wave,src_time,'pchip');
subplot(3,1,1);
plot(src_time, hz5_back, 'b');
hold on;
plot(src_time, src_wave, 'r');
legend('恢复信号','原信号');
title('5hz采样信号恢复图');
subplot(3,1,2);
plot(src_time, hz10_back, 'b');
hold on;
plot(src_time, src_wave, 'r');
legend('恢复信号','原信号');
title('5hz采样信号恢复图');
subplot(3,1,3);
plot(src_time, hz15_back);
hold on;
plot(src_time, src_wave, 'r');
legend('恢复信号','原信号');
title('5hz采样信号恢复图');