input_data = [0, 3, 5, 7, 9, 8, 1, 2, 4, 6];
input_length = length(input_data);
dft_data = my_dft(input_data);
idft_data = my_idft(dft_data);
index_x = linspace(1, input_length, input_length);
stem(index_x, abs(input_data), 'b');
xlabel('n');
ylabel('Amp');
title('原数据与IDFT数据幅度比较图');
hold on;
stem(index_x, abs(idft_data), 'o');
legend('原数据','IDFT数据');
figure;
stem(index_x, phase(input_data), 'b');
xlabel('n');
ylabel('phase');
title('原数据与IDFT数据相位比较图');
hold on;
stem(index_x, phase(idft_data), 'o');
legend('原数据','IDFT数据');