input_data = [0, 3, 5, 7, 9, 8, 1, 2, 4, 6];
input_length = length(input_data);
dft_data = my_dft(input_data);
upsample_data = upsample(input_data, 8);
upsample_dft_data = my_dft(upsample_data);
upsample_x = linspace(1, 8*input_length, 8*input_length);
normal_x = linspace(1, input_length, input_length);
subplot(1,2,1);
stem(normal_x, abs(dft_data), 'b');
xlabel('n');
ylabel('Amp');
title('原数据幅度图');
subplot(1,2,2);
stem(upsample_x, abs(upsample_dft_data), 'o');
xlabel('n');
ylabel('Amp');
title('upsample幅度图');
figure;
subplot(1,2,1);
stem(normal_x, phase(dft_data), 'b');
xlabel('n');
ylabel('phase');
title('原数据相位图');
subplot(1,2,2);
stem(upsample_x, phase(upsample_dft_data), 'o');
xlabel('n');
ylabel('phase');
title('upsample数据相位图');